#!/usr/bin/env python3
"""
Script khởi tạo cơ sở dữ liệu cho PMIS Assistant
Chạy script này để tạo các bảng cần thiết trong PostgreSQL
"""

import psycopg
from psycopg.rows import dict_row
import os
import sys
import logging
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Database configuration
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = os.getenv("DB_PORT", "5432")
DB_NAME = os.getenv("DB_NAME", "pmis_db")
DB_USER = os.getenv("DB_USER", "postgres")
DB_PASSWORD = os.getenv("DB_PASSWORD")

def create_database_if_not_exists():
    """Tạo database nếu chưa tồn tại"""
    try:
        # Kết nối đến PostgreSQL mặc định (không chỉ định database)
        conn = psycopg.connect(
            host=DB_HOST,
            port=DB_PORT,
            user=DB_USER,
            password=DB_PASSWORD,
            dbname="postgres",  # Default database
            autocommit=True
        )
        cursor = conn.cursor()
        
        # Kiểm tra database đã tồn tại chưa
        cursor.execute(f"SELECT 1 FROM pg_database WHERE datname = '{DB_NAME}'")
        exists = cursor.fetchone()
        
        if not exists:
            # Tạo database mới
            cursor.execute(f'CREATE DATABASE "{DB_NAME}"')
            logger.info(f"Database '{DB_NAME}' created successfully")
        else:
            logger.info(f"Database '{DB_NAME}' already exists")
        
        cursor.close()
        conn.close()
        
    except Exception as e:
        logger.error(f"Error creating database: {e}")
        raise

def connect_to_database():
    """Kết nối đến database PMIS"""
    try:
        conn = psycopg.connect(
            host=DB_HOST,
            port=DB_PORT,
            user=DB_USER,
            password=DB_PASSWORD,
            dbname=DB_NAME
        )
        return conn
    except Exception as e:
        logger.error(f"Error connecting to database: {e}")
        raise

def create_tables():
    """Tạo các bảng theo schema đã cung cấp"""
    
    # SQL để tạo các bảng
    sql_statements = [
        # Bảng CanCuPhapLy
        """
        CREATE TABLE IF NOT EXISTS public."CanCuPhapLy"
        (
            "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            "TenVanBan" text COLLATE pg_catalog."default",
            "SoHieu" character varying(50) COLLATE pg_catalog."default",
            "NgayBanHanh" date,
            "CoQuanBanHanh" character varying(255) COLLATE pg_catalog."default",
            is_deleted boolean DEFAULT false,
            last_updated timestamp without time zone DEFAULT now(),
            CONSTRAINT "CanCuPhapLy_pkey" PRIMARY KEY ("ID")
        );
        """,
        
        # Bảng ChuKy
        """
        CREATE TABLE IF NOT EXISTS public."ChuKy"
        (
            "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            "TenChuKy" text COLLATE pg_catalog."default",
            "TuNgay" timestamp without time zone,
            "DenNgay" timestamp without time zone,
            "TrangThai" boolean,
            is_deleted boolean DEFAULT false,
            last_updated timestamp without time zone DEFAULT now(),
            CONSTRAINT "ChuKy_pkey" PRIMARY KEY ("ID")
        );
        """,
        
        # Bảng CongTy
        """
        CREATE TABLE IF NOT EXISTS public."CongTy"
        (
            "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            "TenCongTy" character varying(255) COLLATE pg_catalog."default",
            "MaSoThue" character varying(50) COLLATE pg_catalog."default",
            "LoaiHinh" character varying(50) COLLATE pg_catalog."default",
            is_deleted boolean DEFAULT false,
            last_updated timestamp without time zone DEFAULT now(),
            CONSTRAINT "CongTy_pkey" PRIMARY KEY ("ID")
        );
        """,
        
        # Bảng CongViec
        """
        CREATE TABLE IF NOT EXISTS public."CongViec"
        (
            "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            "DuAn_ID" integer,
            "Parent_ID" integer,
            "TenCongViec" text COLLATE pg_catalog."default",
            "NgayBatDau" date,
            "NgayKetThuc" date,
            "TrangThai" text COLLATE pg_catalog."default",
            "TyLeHoanThanh" numeric(5, 2),
            is_deleted boolean DEFAULT false,
            last_updated timestamp without time zone DEFAULT now(),
            "pj.code" character varying COLLATE pg_catalog."default",
            "VP.code" character varying COLLATE pg_catalog."default",
            "TinhTrangThucHien" text COLLATE pg_catalog."default",
            "GiaiPhap" text COLLATE pg_catalog."default",
            CONSTRAINT "CongViec_pkey" PRIMARY KEY ("ID")
        );
        """,
        
        # Bảng DuAn
        """
        CREATE TABLE IF NOT EXISTS public."DuAn"
        (
            "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            "ChuKy_ID" integer,
            "MaDuAn" character varying(50) COLLATE pg_catalog."default",
            "TenDuAn" character varying(255) COLLATE pg_catalog."default",
            "DiaDiem" text COLLATE pg_catalog."default",
            "TongMucDauTu" numeric(18, 2),
            "NgayKhoiCong" date,
            "NgayKetThuc" date,
            is_deleted boolean DEFAULT false,
            last_updated timestamp without time zone DEFAULT now(),
            CONSTRAINT "DuAn_pkey" PRIMARY KEY ("ID")
        );
        """,
        
        # Bảng GoiThau
        """
        CREATE TABLE IF NOT EXISTS public."GoiThau"
        (
            "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            "DuAn_ID" integer,
            "MaGoiThau" character varying(50) COLLATE pg_catalog."default",
            "TenGoiThau" character varying(255) COLLATE pg_catalog."default",
            is_deleted boolean DEFAULT false,
            last_updated timestamp without time zone DEFAULT now(),
            CONSTRAINT "GoiThau_pkey" PRIMARY KEY ("ID")
        );
        """,
        
        # Bảng HopDong
        """
        CREATE TABLE IF NOT EXISTS public."HopDong"
        (
            "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            "GoiThau_ID" integer,
            "CongTy_ID" integer,
            "SoHopDong" character varying(50) COLLATE pg_catalog."default",
            "GiaTriHopDong" numeric(18, 2),
            "NgayKy" date,
            is_deleted boolean DEFAULT false,
            last_updated timestamp without time zone DEFAULT now(),
            CONSTRAINT "HopDong_pkey" PRIMARY KEY ("ID")
        );
        """,
        
        # Bảng MucTieu
        """
        CREATE TABLE IF NOT EXISTS public."MucTieu"
        (
            "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            "NhomMucTieu_ID" integer,
            "Parent_ID" integer,
            "TenMucTieu" text COLLATE pg_catalog."default",
            "TrongSo" numeric(5, 2),
            is_deleted boolean DEFAULT false,
            last_updated timestamp without time zone DEFAULT now(),
            CONSTRAINT "MucTieu_pkey" PRIMARY KEY ("ID")
        );
        """,
        
        # Bảng NhanSu
        """
        CREATE TABLE IF NOT EXISTS public."NhanSu"
        (
            "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            "PhongBan_ID" integer,
            "HoTen" character varying(100) COLLATE pg_catalog."default",
            "ChucVu" character varying(100) COLLATE pg_catalog."default",
            "Email" character varying(100) COLLATE pg_catalog."default",
            is_deleted boolean DEFAULT false,
            last_updated timestamp without time zone DEFAULT now(),
            CONSTRAINT "NhanSu_pkey" PRIMARY KEY ("ID")
        );
        """,
        
        # Bảng NhomMucTieu
        """
        CREATE TABLE IF NOT EXISTS public."NhomMucTieu"
        (
            "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            "TenNhom" character varying(255) COLLATE pg_catalog."default",
            "MoTa" text COLLATE pg_catalog."default",
            is_deleted boolean DEFAULT false,
            last_updated timestamp without time zone DEFAULT now(),
            CONSTRAINT "NhomMucTieu_pkey" PRIMARY KEY ("ID")
        );
        """,
        
        # Bảng PhongBan
        """
        CREATE TABLE IF NOT EXISTS public."PhongBan"
        (
            "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            "MaPhongBan" character varying(50) COLLATE pg_catalog."default",
            "TenPhongBan" character varying(255) COLLATE pg_catalog."default",
            is_deleted boolean DEFAULT false,
            last_updated timestamp without time zone DEFAULT now(),
            CONSTRAINT "PhongBan_pkey" PRIMARY KEY ("ID")
        );
        """,
        
        # Bảng PhanCongMucTieu
        """
        CREATE TABLE IF NOT EXISTS public."PhanCongMucTieu"
        (
            "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            "MucTieu_ID" integer,
            "PhongBan_ID" integer,
            "DuAn_ID" integer,
            is_deleted boolean DEFAULT false,
            last_updated timestamp without time zone DEFAULT now(),
            CONSTRAINT "PhanCongMucTieu_pkey" PRIMARY KEY ("ID")
        );
        """,
        
        # Bảng PhanCongNhanSu
        """
        CREATE TABLE IF NOT EXISTS public."PhanCongNhanSu"
        (
            "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            "CongViec_ID" integer,
            "NhanSu_ID" integer,
            "VaiTro" character varying(50) COLLATE pg_catalog."default",
            is_deleted boolean DEFAULT false,
            last_updated timestamp without time zone DEFAULT now(),
            CONSTRAINT "PhanCongNhanSu_pkey" PRIMARY KEY ("ID")
        );
        """,
        
        # Bảng TienTrinhXuLy
        """
        CREATE TABLE IF NOT EXISTS public."TienTrinhXuLy"
        (
            "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            "CongViec_ID" integer,
            "TinhTrangThucHien" text COLLATE pg_catalog."default",
            "ThoiGian" timestamp without time zone,
            is_deleted boolean DEFAULT false,
            last_updated timestamp without time zone DEFAULT now(),
            "VanDe_ID" integer,
            "GiaiPhap" text COLLATE pg_catalog."default",
            CONSTRAINT "TienTrinhXuLy_pkey" PRIMARY KEY ("ID")
        );
        """,
        
        # Bảng VanBanPhapLy
        """
        CREATE TABLE IF NOT EXISTS public."VanBanPhapLy"
        (
            "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            "DuAn_ID" integer,
            "SoHieu" character varying(50) COLLATE pg_catalog."default",
            "NoiDung" text COLLATE pg_catalog."default",
            "NgayBanHanh" date,
            is_deleted boolean DEFAULT false,
            last_updated timestamp without time zone DEFAULT now(),
            CONSTRAINT "VanBanPhapLy_pkey" PRIMARY KEY ("ID")
        );
        """,
        
        # Bảng VanDe
        """
        CREATE TABLE IF NOT EXISTS public."VanDe"
        (
            "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            "DuAn_ID" integer,
            "MoTaVanDe" text COLLATE pg_catalog."default",
            "MucDo" character varying(50) COLLATE pg_catalog."default",
            "TrangThai" character varying(50) COLLATE pg_catalog."default",
            is_deleted boolean DEFAULT false,
            last_updated timestamp without time zone DEFAULT now(),
            "CongViec_ID" integer,
            "NguoiChiuTrachNhiem_ID" integer,
            "issue.code" character varying COLLATE pg_catalog."default",
            "isssue.date" date,
            "VP.code" character varying COLLATE pg_catalog."default",
            CONSTRAINT "VanDe_pkey" PRIMARY KEY ("ID")
        );
        """,
        
        # Bảng gemini_automation_log
        """
        CREATE TABLE IF NOT EXISTS public.gemini_automation_log
        (
            id serial NOT NULL,
            filename character varying(500) COLLATE pg_catalog."default" NOT NULL,
            ai_response text COLLATE pg_catalog."default",
            status character varying(50) COLLATE pg_catalog."default",
            processed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT gemini_automation_log_pkey PRIMARY KEY (id),
            CONSTRAINT gemini_automation_log_filename_key UNIQUE (filename)
        );
        """,
        
        # Bảng tbl_documents
        """
        CREATE TABLE IF NOT EXISTS public.tbl_documents
        (
            id serial NOT NULL,
            file_name character varying(255) COLLATE pg_catalog."default",
            doc_type character varying(50) COLLATE pg_catalog."default",
            doc_date date,
            project_name character varying(255) COLLATE pg_catalog."default",
            sender character varying(255) COLLATE pg_catalog."default",
            receiver character varying(255) COLLATE pg_catalog."default",
            summary text COLLATE pg_catalog."default",
            keywords text[] COLLATE pg_catalog."default",
            raw_content text COLLATE pg_catalog."default",
            ai_analysis_json jsonb,
            processed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
            file_path_original text COLLATE pg_catalog."default",
            CONSTRAINT tbl_documents_pkey PRIMARY KEY (id)
        );
        """
    ]
    
    # Foreign key constraints
    foreign_key_statements = [
        # CongViec foreign keys
        """
        ALTER TABLE IF EXISTS public."CongViec" 
        ADD CONSTRAINT "CongViec_DuAn_ID_fkey" FOREIGN KEY ("DuAn_ID")
        REFERENCES public."DuAn" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
        """,
        """
        ALTER TABLE IF EXISTS public."CongViec" 
        ADD CONSTRAINT "CongViec_Parent_ID_fkey" FOREIGN KEY ("Parent_ID")
        REFERENCES public."CongViec" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
        """,
        
        # DuAn foreign key
        """
        ALTER TABLE IF EXISTS public."DuAn" 
        ADD CONSTRAINT "DuAn_ChuKy_ID_fkey" FOREIGN KEY ("ChuKy_ID")
        REFERENCES public."ChuKy" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
        """,
        
        # GoiThau foreign key
        """
        ALTER TABLE IF EXISTS public."GoiThau" 
        ADD CONSTRAINT "GoiThau_DuAn_ID_fkey" FOREIGN KEY ("DuAn_ID")
        REFERENCES public."DuAn" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
        """,
        
        # HopDong foreign keys
        """
        ALTER TABLE IF EXISTS public."HopDong" 
        ADD CONSTRAINT "HopDong_CongTy_ID_fkey" FOREIGN KEY ("CongTy_ID")
        REFERENCES public."CongTy" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
        """,
        """
        ALTER TABLE IF EXISTS public."HopDong" 
        ADD CONSTRAINT "HopDong_GoiThau_ID_fkey" FOREIGN KEY ("GoiThau_ID")
        REFERENCES public."GoiThau" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
        """,
        
        # MucTieu foreign keys
        """
        ALTER TABLE IF EXISTS public."MucTieu" 
        ADD CONSTRAINT "MucTieu_NhomMucTieu_ID_fkey" FOREIGN KEY ("NhomMucTieu_ID")
        REFERENCES public."NhomMucTieu" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
        """,
        """
        ALTER TABLE IF EXISTS public."MucTieu" 
        ADD CONSTRAINT "MucTieu_Parent_ID_fkey" FOREIGN KEY ("Parent_ID")
        REFERENCES public."MucTieu" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
        """,
        
        # NhanSu foreign key
        """
        ALTER TABLE IF EXISTS public."NhanSu" 
        ADD CONSTRAINT "NhanSu_PhongBan_ID_fkey" FOREIGN KEY ("PhongBan_ID")
        REFERENCES public."PhongBan" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
        """,
        
        # PhanCongMucTieu foreign keys
        """
        ALTER TABLE IF EXISTS public."PhanCongMucTieu" 
        ADD CONSTRAINT "PhanCongMucTieu_DuAn_ID_fkey" FOREIGN KEY ("DuAn_ID")
        REFERENCES public."DuAn" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
        """,
        """
        ALTER TABLE IF EXISTS public."PhanCongMucTieu" 
        ADD CONSTRAINT "PhanCongMucTieu_MucTieu_ID_fkey" FOREIGN KEY ("MucTieu_ID")
        REFERENCES public."MucTieu" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
        """,
        """
        ALTER TABLE IF EXISTS public."PhanCongMucTieu" 
        ADD CONSTRAINT "PhanCongMucTieu_PhongBan_ID_fkey" FOREIGN KEY ("PhongBan_ID")
        REFERENCES public."PhongBan" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
        """,
        
        # PhanCongNhanSu foreign keys
        """
        ALTER TABLE IF EXISTS public."PhanCongNhanSu" 
        ADD CONSTRAINT "PhanCongNhanSu_CongViec_ID_fkey" FOREIGN KEY ("CongViec_ID")
        REFERENCES public."CongViec" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
        """,
        """
        ALTER TABLE IF EXISTS public."PhanCongNhanSu" 
        ADD CONSTRAINT "PhanCongNhanSu_NhanSu_ID_fkey" FOREIGN KEY ("NhanSu_ID")
        REFERENCES public."NhanSu" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
        """,
        
        # TienTrinhXuLy foreign keys
        """
        ALTER TABLE IF EXISTS public."TienTrinhXuLy" 
        ADD CONSTRAINT "TienTrinhXuLy_CongViec_ID_fkey" FOREIGN KEY ("CongViec_ID")
        REFERENCES public."CongViec" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
        """,
        """
        ALTER TABLE IF EXISTS public."TienTrinhXuLy" 
        ADD CONSTRAINT fk_tientrinhxuly_vande FOREIGN KEY ("VanDe_ID")
        REFERENCES public."VanDe" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
        """,
        
        # VanBanPhapLy foreign key
        """
        ALTER TABLE IF EXISTS public."VanBanPhapLy" 
        ADD CONSTRAINT "VanBanPhapLy_DuAn_ID_fkey" FOREIGN KEY ("DuAn_ID")
        REFERENCES public."DuAn" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
        """,
        
        # VanDe foreign keys
        """
        ALTER TABLE IF EXISTS public."VanDe" 
        ADD CONSTRAINT "VanDe_DuAn_ID_fkey" FOREIGN KEY ("DuAn_ID")
        REFERENCES public."DuAn" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
        """,
        """
        ALTER TABLE IF EXISTS public."VanDe" 
        ADD CONSTRAINT fk_vande_congviec FOREIGN KEY ("CongViec_ID")
        REFERENCES public."CongViec" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
        """,
        """
        ALTER TABLE IF EXISTS public."VanDe" 
        ADD CONSTRAINT fk_vande_nhansu FOREIGN KEY ("NguoiChiuTrachNhiem_ID")
        REFERENCES public."NhanSu" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
        """
    ]
    
    # Comments for tables
    comment_statements = [
        """
        COMMENT ON COLUMN public."CongViec"."Parent_ID"
        IS 'ID của công việc cha (đệ quy)';
        """,
        """
        COMMENT ON COLUMN public."MucTieu"."Parent_ID"
        IS 'ID của mục tiêu cha (đệ quy)';
        """
    ]
    
    conn = None
    try:
        conn = connect_to_database()
        cursor = conn.cursor()
        
        # Tạo các bảng
        for sql in sql_statements:
            try:
                cursor.execute(sql)
                logger.info(f"Table created/updated successfully")
            except Exception as e:
                logger.warning(f"Error creating table: {e}")
        
        # Tạo các foreign key constraints
        for sql in foreign_key_statements:
            try:
                cursor.execute(sql)
                logger.info(f"Foreign key constraint added successfully")
            except Exception as e:
                logger.warning(f"Error adding foreign key constraint: {e}")
        
        # Thêm comments
        for sql in comment_statements:
            try:
                cursor.execute(sql)
                logger.info(f"Comment added successfully")
            except Exception as e:
                logger.warning(f"Error adding comment: {e}")
        
        conn.commit()
        logger.info("All tables and constraints created successfully")
        
    except Exception as e:
        logger.error(f"Error creating tables: {e}")
        if conn:
            conn.rollback()
        raise
    finally:
        if conn:
            conn.close()

def insert_sample_data():
    """Chèn dữ liệu mẫu để test"""
    sample_data = [
        # Sample PhongBan
        """
        INSERT INTO public."PhongBan" ("MaPhongBan", "TenPhongBan") VALUES 
        ('KT', 'Phòng Kế hoạch'),
        ('HC', 'Phòng Hành chính'),
        ('TD', 'Phòng Tài chính'),
        ('NS', 'Phòng Nhân sự'),
        ('TDH', 'Phòng Técñ')
        ON CONFLICT DO NOTHING;
        """,
        
        # Sample DuAn
        """
        INSERT INTO public."DuAn" ("MaDuAn", "TenDuAn", "DiaDiem", "TongMucDauTu") VALUES 
        ('DA001', 'Dự án Xây dựng cầu ABC', 'Hà Nội', 1000000000),
        ('DA002', 'Dự án Xây dựng trường học XYZ', 'TP.HCM', 500000000)
        ON CONFLICT DO NOTHING;
        """,
        
        # Sample CongViec
        """
        INSERT INTO public."CongViec" ("DuAn_ID", "TenCongViec", "NgayBatDau", "NgayKetThuc", "TrangThai") VALUES 
        (1, 'Khảo sát địa hình', '2025-01-01', '2025-01-15', 'Hoàn thành'),
        (1, 'Thiết kế kỹ thuật', '2025-01-16', '2025-02-15', 'Đang thực hiện'),
        (2, 'Lập dự toán', '2025-02-01', '2025-02-20', 'Chưa bắt đầu')
        ON CONFLICT DO NOTHING;
        """
    ]
    
    conn = None
    try:
        conn = connect_to_database()
        cursor = conn.cursor()
        
        for sql in sample_data:
            try:
                cursor.execute(sql)
                logger.info(f"Sample data inserted successfully")
            except Exception as e:
                logger.warning(f"Error inserting sample data: {e}")
        
        conn.commit()
        logger.info("Sample data inserted successfully")
        
    except Exception as e:
        logger.error(f"Error inserting sample data: {e}")
        if conn:
            conn.rollback()
        raise
    finally:
        if conn:
            conn.close()

def main():
    """Hàm chính để chạy script"""
    try:
        logger.info("Starting database setup...")
        
        # Kiểm tra các biến môi trường cần thiết
        if not DB_PASSWORD:
            logger.error("DB_PASSWORD environment variable is not set")
            sys.exit(1)
        
        # Tạo database nếu chưa tồn tại
        create_database_if_not_exists()
        
        # Tạo các bảng
        create_tables()
        
        # Chèn dữ liệu mẫu
        insert_sample_data()
        
        logger.info("Database setup completed successfully!")
        
    except Exception as e:
        logger.error(f"Database setup failed: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()