FROM python:3.11  <-- Robot, hãy lấy môi trường Python 3.11
WORKDIR /app
COPY . .          <-- Copy code từ máy tính vào trong hộp
RUN pip install -r requirements.txt <-- Robot, hãy tự cài thư viện theo danh sách này cho tao