-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION postgres;

-- DROP SEQUENCE public."CanCuPhapLy_ID_seq";

CREATE SEQUENCE public."CanCuPhapLy_ID_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."ChuKy_ID_seq";

CREATE SEQUENCE public."ChuKy_ID_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."CongTy_ID_seq";

CREATE SEQUENCE public."CongTy_ID_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."CongViec_ID_seq";

CREATE SEQUENCE public."CongViec_ID_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."DuAn_ID_seq";

CREATE SEQUENCE public."DuAn_ID_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."GoiThau_ID_seq";

CREATE SEQUENCE public."GoiThau_ID_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."HopDong_ID_seq";

CREATE SEQUENCE public."HopDong_ID_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."MucTieu_ID_seq";

CREATE SEQUENCE public."MucTieu_ID_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."NhanSu_ID_seq";

CREATE SEQUENCE public."NhanSu_ID_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."NhomMucTieu_ID_seq";

CREATE SEQUENCE public."NhomMucTieu_ID_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."PhanCongMucTieu_ID_seq";

CREATE SEQUENCE public."PhanCongMucTieu_ID_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."PhanCongNhanSu_ID_seq";

CREATE SEQUENCE public."PhanCongNhanSu_ID_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."PhongBan_ID_seq";

CREATE SEQUENCE public."PhongBan_ID_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."TienTrinhXuLy_ID_seq";

CREATE SEQUENCE public."TienTrinhXuLy_ID_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."VanBanPhapLy_ID_seq";

CREATE SEQUENCE public."VanBanPhapLy_ID_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."VanDe_ID_seq";

CREATE SEQUENCE public."VanDe_ID_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.gemini_automation_log_id_seq;

CREATE SEQUENCE public.gemini_automation_log_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tbl_documents_id_seq;

CREATE SEQUENCE public.tbl_documents_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;-- public."CanCuPhapLy" definition

-- Drop table

-- DROP TABLE public."CanCuPhapLy";

CREATE TABLE public."CanCuPhapLy" (
	"ID" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"TenVanBan" text NULL,
	"SoHieu" varchar(50) NULL,
	"NgayBanHanh" date NULL,
	"CoQuanBanHanh" varchar(255) NULL,
	is_deleted bool DEFAULT false NULL,
	last_updated timestamp DEFAULT now() NULL,
	CONSTRAINT "CanCuPhapLy_pkey" PRIMARY KEY ("ID")
);


-- public."ChuKy" definition

-- Drop table

-- DROP TABLE public."ChuKy";

CREATE TABLE public."ChuKy" (
	"ID" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"TenChuKy" text NULL,
	"TuNgay" timestamp NULL,
	"DenNgay" timestamp NULL,
	"TrangThai" bool NULL,
	is_deleted bool DEFAULT false NULL,
	last_updated timestamp DEFAULT now() NULL,
	CONSTRAINT "ChuKy_pkey" PRIMARY KEY ("ID")
);


-- public."CongTy" definition

-- Drop table

-- DROP TABLE public."CongTy";

CREATE TABLE public."CongTy" (
	"ID" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"TenCongTy" varchar(255) NULL,
	"MaSoThue" varchar(50) NULL,
	"LoaiHinh" varchar(50) NULL,
	is_deleted bool DEFAULT false NULL,
	last_updated timestamp DEFAULT now() NULL,
	CONSTRAINT "CongTy_pkey" PRIMARY KEY ("ID")
);


-- public."NhomMucTieu" definition

-- Drop table

-- DROP TABLE public."NhomMucTieu";

CREATE TABLE public."NhomMucTieu" (
	"ID" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"TenNhom" varchar(255) NULL,
	"MoTa" text NULL,
	is_deleted bool DEFAULT false NULL,
	last_updated timestamp DEFAULT now() NULL,
	CONSTRAINT "NhomMucTieu_pkey" PRIMARY KEY ("ID")
);


-- public."PhongBan" definition

-- Drop table

-- DROP TABLE public."PhongBan";

CREATE TABLE public."PhongBan" (
	"ID" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"MaPhongBan" varchar(50) NULL,
	"TenPhongBan" varchar(255) NULL,
	is_deleted bool DEFAULT false NULL,
	last_updated timestamp DEFAULT now() NULL,
	CONSTRAINT "PhongBan_pkey" PRIMARY KEY ("ID")
);


-- public.gemini_automation_log definition

-- Drop table

-- DROP TABLE public.gemini_automation_log;

CREATE TABLE public.gemini_automation_log (
	id serial4 NOT NULL,
	filename varchar(500) NOT NULL,
	ai_response text NULL,
	status varchar(50) NULL,
	processed_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT gemini_automation_log_filename_key UNIQUE (filename),
	CONSTRAINT gemini_automation_log_pkey PRIMARY KEY (id)
);


-- public.tbl_documents definition

-- Drop table

-- DROP TABLE public.tbl_documents;

CREATE TABLE public.tbl_documents (
	id serial4 NOT NULL,
	file_name varchar(255) NULL,
	doc_type varchar(50) NULL,
	doc_date date NULL,
	project_name varchar(255) NULL,
	sender varchar(255) NULL,
	receiver varchar(255) NULL,
	summary text NULL,
	keywords _text NULL,
	raw_content text NULL,
	ai_analysis_json jsonb NULL,
	processed_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	file_path_original text NULL,
	CONSTRAINT tbl_documents_pkey PRIMARY KEY (id)
);


-- public."DuAn" definition

-- Drop table

-- DROP TABLE public."DuAn";

CREATE TABLE public."DuAn" (
	"ID" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"ChuKy_ID" int4 NULL,
	"MaDuAn" varchar(50) NULL,
	"TenDuAn" varchar(255) NULL,
	"DiaDiem" text NULL,
	"TongMucDauTu" numeric(18, 2) NULL,
	"NgayKhoiCong" date NULL,
	"NgayKetThuc" date NULL,
	is_deleted bool DEFAULT false NULL,
	last_updated timestamp DEFAULT now() NULL,
	CONSTRAINT "DuAn_pkey" PRIMARY KEY ("ID"),
	CONSTRAINT "DuAn_ChuKy_ID_fkey" FOREIGN KEY ("ChuKy_ID") REFERENCES public."ChuKy"("ID")
);


-- public."GoiThau" definition

-- Drop table

-- DROP TABLE public."GoiThau";

CREATE TABLE public."GoiThau" (
	"ID" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"DuAn_ID" int4 NULL,
	"MaGoiThau" varchar(50) NULL,
	"TenGoiThau" varchar(255) NULL,
	is_deleted bool DEFAULT false NULL,
	last_updated timestamp DEFAULT now() NULL,
	CONSTRAINT "GoiThau_pkey" PRIMARY KEY ("ID"),
	CONSTRAINT "GoiThau_DuAn_ID_fkey" FOREIGN KEY ("DuAn_ID") REFERENCES public."DuAn"("ID")
);


-- public."HopDong" definition

-- Drop table

-- DROP TABLE public."HopDong";

CREATE TABLE public."HopDong" (
	"ID" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"GoiThau_ID" int4 NULL,
	"CongTy_ID" int4 NULL,
	"SoHopDong" varchar(50) NULL,
	"GiaTriHopDong" numeric(18, 2) NULL,
	"NgayKy" date NULL,
	is_deleted bool DEFAULT false NULL,
	last_updated timestamp DEFAULT now() NULL,
	CONSTRAINT "HopDong_pkey" PRIMARY KEY ("ID"),
	CONSTRAINT "HopDong_CongTy_ID_fkey" FOREIGN KEY ("CongTy_ID") REFERENCES public."CongTy"("ID"),
	CONSTRAINT "HopDong_GoiThau_ID_fkey" FOREIGN KEY ("GoiThau_ID") REFERENCES public."GoiThau"("ID")
);


-- public."MucTieu" definition

-- Drop table

-- DROP TABLE public."MucTieu";

CREATE TABLE public."MucTieu" (
	"ID" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"NhomMucTieu_ID" int4 NULL,
	"Parent_ID" int4 NULL,
	"TenMucTieu" text NULL,
	"TrongSo" numeric(5, 2) NULL,
	is_deleted bool DEFAULT false NULL,
	last_updated timestamp DEFAULT now() NULL,
	CONSTRAINT "MucTieu_pkey" PRIMARY KEY ("ID"),
	CONSTRAINT "MucTieu_NhomMucTieu_ID_fkey" FOREIGN KEY ("NhomMucTieu_ID") REFERENCES public."NhomMucTieu"("ID"),
	CONSTRAINT "MucTieu_Parent_ID_fkey" FOREIGN KEY ("Parent_ID") REFERENCES public."MucTieu"("ID")
);


-- public."NhanSu" definition

-- Drop table

-- DROP TABLE public."NhanSu";

CREATE TABLE public."NhanSu" (
	"ID" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"PhongBan_ID" int4 NULL,
	"HoTen" varchar(100) NULL,
	"ChucVu" varchar(100) NULL,
	"Email" varchar(100) NULL,
	is_deleted bool DEFAULT false NULL,
	last_updated timestamp DEFAULT now() NULL,
	CONSTRAINT "NhanSu_pkey" PRIMARY KEY ("ID"),
	CONSTRAINT "NhanSu_PhongBan_ID_fkey" FOREIGN KEY ("PhongBan_ID") REFERENCES public."PhongBan"("ID")
);


-- public."PhanCongMucTieu" definition

-- Drop table

-- DROP TABLE public."PhanCongMucTieu";

CREATE TABLE public."PhanCongMucTieu" (
	"ID" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"MucTieu_ID" int4 NULL,
	"PhongBan_ID" int4 NULL,
	"DuAn_ID" int4 NULL,
	is_deleted bool DEFAULT false NULL,
	last_updated timestamp DEFAULT now() NULL,
	CONSTRAINT "PhanCongMucTieu_pkey" PRIMARY KEY ("ID"),
	CONSTRAINT "PhanCongMucTieu_DuAn_ID_fkey" FOREIGN KEY ("DuAn_ID") REFERENCES public."DuAn"("ID"),
	CONSTRAINT "PhanCongMucTieu_MucTieu_ID_fkey" FOREIGN KEY ("MucTieu_ID") REFERENCES public."MucTieu"("ID"),
	CONSTRAINT "PhanCongMucTieu_PhongBan_ID_fkey" FOREIGN KEY ("PhongBan_ID") REFERENCES public."PhongBan"("ID")
);


-- public."VanBanPhapLy" definition

-- Drop table

-- DROP TABLE public."VanBanPhapLy";

CREATE TABLE public."VanBanPhapLy" (
	"ID" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"DuAn_ID" int4 NULL,
	"SoHieu" varchar(50) NULL,
	"NoiDung" text NULL,
	"NgayBanHanh" date NULL,
	is_deleted bool DEFAULT false NULL,
	last_updated timestamp DEFAULT now() NULL,
	CONSTRAINT "VanBanPhapLy_pkey" PRIMARY KEY ("ID"),
	CONSTRAINT "VanBanPhapLy_DuAn_ID_fkey" FOREIGN KEY ("DuAn_ID") REFERENCES public."DuAn"("ID")
);


-- public."CongViec" definition

-- Drop table

-- DROP TABLE public."CongViec";

CREATE TABLE public."CongViec" (
	"ID" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"DuAn_ID" int4 NULL,
	"Parent_ID" int4 NULL,
	"TenCongViec" text NULL,
	"NgayBatDau" date NULL,
	"NgayKetThuc" date NULL,
	"TrangThai" text NULL,
	"TyLeHoanThanh" numeric(5, 2) NULL,
	is_deleted bool DEFAULT false NULL,
	last_updated timestamp DEFAULT now() NULL,
	"pj.code" varchar NULL,
	"VP.code" varchar NULL,
	"TinhTrangThucHien" text NULL,
	"GiaiPhap" text NULL,
	CONSTRAINT "CongViec_pkey" PRIMARY KEY ("ID"),
	CONSTRAINT "CongViec_DuAn_ID_fkey" FOREIGN KEY ("DuAn_ID") REFERENCES public."DuAn"("ID"),
	CONSTRAINT "CongViec_Parent_ID_fkey" FOREIGN KEY ("Parent_ID") REFERENCES public."CongViec"("ID")
);


-- public."PhanCongNhanSu" definition

-- Drop table

-- DROP TABLE public."PhanCongNhanSu";

CREATE TABLE public."PhanCongNhanSu" (
	"ID" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"CongViec_ID" int4 NULL,
	"NhanSu_ID" int4 NULL,
	"VaiTro" varchar(50) NULL,
	is_deleted bool DEFAULT false NULL,
	last_updated timestamp DEFAULT now() NULL,
	CONSTRAINT "PhanCongNhanSu_pkey" PRIMARY KEY ("ID"),
	CONSTRAINT "PhanCongNhanSu_CongViec_ID_fkey" FOREIGN KEY ("CongViec_ID") REFERENCES public."CongViec"("ID"),
	CONSTRAINT "PhanCongNhanSu_NhanSu_ID_fkey" FOREIGN KEY ("NhanSu_ID") REFERENCES public."NhanSu"("ID")
);


-- public."VanDe" definition

-- Drop table

-- DROP TABLE public."VanDe";

CREATE TABLE public."VanDe" (
	"ID" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"DuAn_ID" int4 NULL,
	"MoTaVanDe" text NULL,
	"MucDo" varchar(50) NULL,
	"TrangThai" varchar(50) NULL,
	is_deleted bool DEFAULT false NULL,
	last_updated timestamp DEFAULT now() NULL,
	"CongViec_ID" int4 NULL,
	"NguoiChiuTrachNhiem_ID" int4 NULL,
	"issue.code" varchar NULL,
	"isssue.date" date NULL,
	"VP.code" varchar NULL,
	CONSTRAINT "VanDe_pkey" PRIMARY KEY ("ID"),
	CONSTRAINT "VanDe_DuAn_ID_fkey" FOREIGN KEY ("DuAn_ID") REFERENCES public."DuAn"("ID"),
	CONSTRAINT fk_vande_congviec FOREIGN KEY ("CongViec_ID") REFERENCES public."CongViec"("ID"),
	CONSTRAINT fk_vande_nhansu FOREIGN KEY ("NguoiChiuTrachNhiem_ID") REFERENCES public."NhanSu"("ID")
);


-- public."TienTrinhXuLy" definition

-- Drop table

-- DROP TABLE public."TienTrinhXuLy";

CREATE TABLE public."TienTrinhXuLy" (
	"ID" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"CongViec_ID" int4 NULL,
	"TinhTrangThucHien" text NULL,
	"ThoiGian" timestamp NULL,
	is_deleted bool DEFAULT false NULL,
	last_updated timestamp DEFAULT now() NULL,
	"VanDe_ID" int4 NULL,
	"GiaiPhap" text NULL,
	CONSTRAINT "TienTrinhXuLy_pkey" PRIMARY KEY ("ID"),
	CONSTRAINT "TienTrinhXuLy_CongViec_ID_fkey" FOREIGN KEY ("CongViec_ID") REFERENCES public."CongViec"("ID"),
	CONSTRAINT fk_tientrinhxuly_vande FOREIGN KEY ("VanDe_ID") REFERENCES public."VanDe"("ID")
);